# This is a GitHub actions workflow for the NCEPLIBS-prod_util project.
#
# This workflow builds with the Intel Classic and OneAPI compilers.
#
# Alex Richert, Sep 2023
name: Intel
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Intel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compilers: ["oneapi", "classic"]

    steps:

    - name: "Install Intel"
      uses: NOAA-EMC/ci-install-intel-toolkit@develop
      with:
        compiler-setup: ${{ matrix.compilers }}

    - name: "Build dependencies"
      uses: NOAA-EMC/ci-build-nceplibs@develop
      with:
        bacio-version: v2.6.0
        w3emc-version: v2.10.0
        w3emc-cmake-args: -DBUILD_WITH_BUFR=OFF

    - name: checkout-prod_util
      uses: actions/checkout@v4
      with:
        path: prod_util

    - name: build-prod_util
      run: |
        cmake -S prod_util -B prod_util/build -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-bacio;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-w3emc" 
        cmake --build prod_util/build --parallel 2 --verbose
        ctest --test-dir prod_util/build --output-on-failure --verbose
