# This is a GitHub actions workflow for the NCEPLIBS-prod_util project.
#
# This workflow builds with GCC
#
# Alex Richert, Sep 2023, Ed Hartnett
name: Linux_versions
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Linux_versions:
    runs-on: ubuntu-latest
    env:
      FC: gfortran
      CC: gcc
    strategy:
      fail-fast: true
      matrix:
        bacio-version: [2.4.1, 2.5.0, 2.6.0]
        w3emc-version: [2.9.3, 2.10.0, 2.11.0]

    steps:


    - name: "Build dependencies"
      uses: NOAA-EMC/ci-build-nceplibs@develop
      with:
        bacio-version: ${{ matrix.bacio-version }}
        w3emc-version: ${{ matrix.w3emc-version }}
        w3emc-cmake-args: -DBUILD_WITH_BUFR=OFF

    - name: checkout-prod_util
      uses: actions/checkout@v4
      with:
        path: prod_util

    - name: build-prod_util
      run: |
        cmake -S prod_util -B prod_util/build -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-bacio;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-w3emc" 
        cmake --build prod_util/build --parallel 2 --verbose
        ctest --test-dir prod_util/build --output-on-failure --verbose
